# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import msg_pb2 as msg__pb2


class OrpheusStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Init = channel.unary_unary(
        '/Orpheus/Init',
        request_serializer=msg__pb2.InitRequest.SerializeToString,
        response_deserializer=msg__pb2.BasicReply.FromString,
        )
    self.List = channel.unary_unary(
        '/Orpheus/List',
        request_serializer=msg__pb2.Empty.SerializeToString,
        response_deserializer=msg__pb2.BasicReply.FromString,
        )
    self.Drop = channel.unary_unary(
        '/Orpheus/Drop',
        request_serializer=msg__pb2.DropRequest.SerializeToString,
        response_deserializer=msg__pb2.BasicReply.FromString,
        )


class OrpheusServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Init(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Drop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OrpheusServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Init': grpc.unary_unary_rpc_method_handler(
          servicer.Init,
          request_deserializer=msg__pb2.InitRequest.FromString,
          response_serializer=msg__pb2.BasicReply.SerializeToString,
      ),
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=msg__pb2.Empty.FromString,
          response_serializer=msg__pb2.BasicReply.SerializeToString,
      ),
      'Drop': grpc.unary_unary_rpc_method_handler(
          servicer.Drop,
          request_deserializer=msg__pb2.DropRequest.FromString,
          response_serializer=msg__pb2.BasicReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Orpheus', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
